<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Flights</name>
   <tag></tag>
   <elementGuidId>84a69b83-c100-4f72-898a-2b8d726f5e1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flights</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='flights']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;header-xpb&quot;] >> internal:role=link[name=&quot;Flights&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a493e7ee-44d3-40b6-bcc7-7395e3854ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flights</value>
      <webElementGuid>1575ab41-c15d-4b49-a55c-b4f6cc0717ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6023042a-e85f-4453-8a26-617ae5551df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ch.booking.com/c?st=RkxJR0hU&amp;rid=745ce3e1-ba41-11ef-af8f-6fb4c2956d35&amp;lt=TEFORElOR19QQUdF&amp;target=aHR0cHM6Ly93d3cuYm9va2luZy5jb20vZmxpZ2h0cy9pbmRleC5lbi1nYi5odG1sP2FkcGxhdD13d3ctdW5rbm93bi13ZWJfc2hlbGxfaGVhZGVyLWZsaWdodC1taXNzaW5nX2NyZWF0aXZlLTMzbVpIMU9CSzhXbnNjcm45dDNHcDEmYWlkPTIxNDgwMzYmY2xpZW50X25hbWU9Yi13ZWItc2hlbGwtYmZmJmV0U3RhdGVCbG9iPUVhRXpkMEFlNkxld0JsOS0xOUVqY3QxWHdiTUk2enpBQnM3aGFVeTFsYXdna0w4Y1JiWDlhSFVFQTQ1dzR1YThDJmRpc3RyaWJ1dGlvbl9pZD0zM21aSDFPQks4V25zY3JuOXQzR3Ax</value>
      <webElementGuid>0b0cfc0b-3a30-4004-bfe0-b40f4e70a5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a83ed08757 f3441ccb97 ec66406250</value>
      <webElementGuid>1acf1758-27b7-4b11-b379-932f93d768f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Flights</value>
      <webElementGuid>6d35e9b6-3049-4649-8fec-d8a6b216fa2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flights&quot;)</value>
      <webElementGuid>280daab1-a7ea-4104-a4c0-436a7aec6b3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='flights']</value>
      <webElementGuid>ffa4336c-e88c-43e8-89cf-ba7c439f4158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/header/div/nav[2]/div/ul/li[2]/a</value>
      <webElementGuid>00a17722-cb9e-4c4b-adfb-06092a35276c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stays'])[1]/following::a[1]</value>
      <webElementGuid>f65ab390-695a-49db-8f63-31d9dc49f6bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::a[2]</value>
      <webElementGuid>83ccbb34-bdbc-4bb5-9ac6-b98c9be8ad7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight + Hotel'])[1]/preceding::a[1]</value>
      <webElementGuid>4911d5cf-61ea-4b82-89e8-f0eac5739d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ch.booking.com/c?st=RkxJR0hU&amp;rid=745ce3e1-ba41-11ef-af8f-6fb4c2956d35&amp;lt=TEFORElOR19QQUdF&amp;target=aHR0cHM6Ly93d3cuYm9va2luZy5jb20vZmxpZ2h0cy9pbmRleC5lbi1nYi5odG1sP2FkcGxhdD13d3ctdW5rbm93bi13ZWJfc2hlbGxfaGVhZGVyLWZsaWdodC1taXNzaW5nX2NyZWF0aXZlLTMzbVpIMU9CSzhXbnNjcm45dDNHcDEmYWlkPTIxNDgwMzYmY2xpZW50X25hbWU9Yi13ZWItc2hlbGwtYmZmJmV0U3RhdGVCbG9iPUVhRXpkMEFlNkxld0JsOS0xOUVqY3QxWHdiTUk2enpBQnM3aGFVeTFsYXdna0w4Y1JiWDlhSFVFQTQ1dzR1YThDJmRpc3RyaWJ1dGlvbl9pZD0zM21aSDFPQks4V25zY3JuOXQzR3Ax')]</value>
      <webElementGuid>1811f206-e0bb-4ed4-88de-adc4ecdaabb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>0e184e37-2c68-4458-9f84-4382321bf90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'flights' and @href = 'https://ch.booking.com/c?st=RkxJR0hU&amp;rid=745ce3e1-ba41-11ef-af8f-6fb4c2956d35&amp;lt=TEFORElOR19QQUdF&amp;target=aHR0cHM6Ly93d3cuYm9va2luZy5jb20vZmxpZ2h0cy9pbmRleC5lbi1nYi5odG1sP2FkcGxhdD13d3ctdW5rbm93bi13ZWJfc2hlbGxfaGVhZGVyLWZsaWdodC1taXNzaW5nX2NyZWF0aXZlLTMzbVpIMU9CSzhXbnNjcm45dDNHcDEmYWlkPTIxNDgwMzYmY2xpZW50X25hbWU9Yi13ZWItc2hlbGwtYmZmJmV0U3RhdGVCbG9iPUVhRXpkMEFlNkxld0JsOS0xOUVqY3QxWHdiTUk2enpBQnM3aGFVeTFsYXdna0w4Y1JiWDlhSFVFQTQ1dzR1YThDJmRpc3RyaWJ1dGlvbl9pZD0zM21aSDFPQks4V25zY3JuOXQzR3Ax' and (text() = 'Flights' or . = 'Flights')]</value>
      <webElementGuid>f455fb1f-89fa-4612-949f-93eb398a5ee7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
