<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Age 18_Actionable-module__root___ph-_9f444b</name>
   <tag></tag>
   <elementGuidId>594fcdad-56c8-4c16-8350-cf164e2b0f93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[24]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.InputStepper-module__wrapper___fptXK > button:nth-child(3) >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>407092d4-1cb7-4d8b-b2d9-0a7e3b45dd72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>fbd9f976-9744-47a3-89b5-05d6cf51e542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3bbd121e-642a-43d8-b034-9cb9fd8ab879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a8907ba4-47e3-45e2-b163-2238e268072c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Actionable-module__root___ph-jy Button-module__root___RNgyk Button-module__root--variant-tertiary___4CkZL Button-module__root--icon-only___dkWUE Button-module__root--size-medium___fCFP3 Button-module__root--variant-tertiary-action___7tY+8 InputStepper-module__add___RF0oT</value>
      <webElementGuid>e4ec6aaa-445e-43f8-a089-9f3c776b5b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui-name</name>
      <type>Main</type>
      <value>button_occupancy_adults_plus</value>
      <webElementGuid>f3a4b473-9c10-4e45-a23c-626dcfb072e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:R4tl1995:&quot;)/div[@class=&quot;Flyout-module__inner___yOVSv Popover-module__root___Hbald Popover-module__root--fill___GfL+b&quot;]/div[@class=&quot;OccupancyDropDown-module__content___ve5Q2&quot;]/div[@class=&quot;OccupancyDropDown-module__contentScrollArea___l4V1X&quot;]/div[@class=&quot;Occupancy-module__wrapper___URu7B&quot;]/div[@class=&quot;Adults-module__wrapper___YqBUC&quot;]/div[@class=&quot;InputStepper-module__root___zlers&quot;]/div[@class=&quot;InputStepper-module__wrapper___fptXK&quot;]/button[@class=&quot;Actionable-module__root___ph-jy Button-module__root___RNgyk Button-module__root--variant-tertiary___4CkZL Button-module__root--icon-only___dkWUE Button-module__root--size-medium___fCFP3 Button-module__root--variant-tertiary-action___7tY+8 InputStepper-module__add___RF0oT&quot;]</value>
      <webElementGuid>2bd0af06-1fb6-4c60-8732-bbd38bbe203e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[24]</value>
      <webElementGuid>1ce4915f-f41d-4c50-badc-2294c90a32d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':R4tl1995:']/div/div/div/div/div/div/div[2]/button[2]</value>
      <webElementGuid>205f3a4f-597c-451e-b543-5277aee16381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age 18+'])[1]/following::button[2]</value>
      <webElementGuid>398ebb3c-5b82-49b1-bf47-001b9192ac2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adults'])[1]/following::button[2]</value>
      <webElementGuid>e3393995-c3f4-4713-aaf3-ad47b91b4ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Children'])[1]/preceding::button[1]</value>
      <webElementGuid>ae6553ca-10c7-4d22-85c7-366561f11fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age 0 - 17'])[1]/preceding::button[1]</value>
      <webElementGuid>6ab916fa-6bde-4f99-b5d6-8908bc27b161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>9247cf42-d538-40ef-8659-2dc22918b937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>780fb2de-3a74-4a92-96f4-f95dee19cc8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
