<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Accept_AutoComplete-module__textInput_abe6fe_1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>ed54b31c-49b6-43ad-a9e6-917c73056052</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.AutoComplete-module__textInput___Qh3I-</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Rio De j']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Airport or city&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>abb1c4b2-0f35-4ca5-aa12-77cdbf8f0c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AutoComplete-module__textInput___Qh3I- </value>
      <webElementGuid>ae39d7f3-c081-4c97-8918-375e317e0964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Airport or city</value>
      <webElementGuid>6ce56fde-ad5a-448c-a578-c93b4dcd1f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a41b3e45-4a7c-4935-978d-e625fb93630e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui-name</name>
      <type>Main</type>
      <value>input_text_autocomplete</value>
      <webElementGuid>9f324a6c-5718-4ee8-a203-13760178574c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>687c24dd-2e44-4c71-8f2d-d9c6bd87ebd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>flights-searchbox_suggestions</value>
      <webElementGuid>edcd690d-fe54-4af6-95b6-229a9429596f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>de744b63-c6c9-4803-93a7-5bea0cfee363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Rio De j</value>
      <webElementGuid>c23c3a53-66dc-4c89-af8b-a23d4afca2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:R16dl1995:&quot;)/div[@class=&quot;Flyout-module__inner___yOVSv Popover-module__root___Hbald&quot;]/div[@class=&quot;LocationsDropDown-module__container___BjM+P&quot;]/div[@class=&quot;AutoComplete-module__wrapper___d3PlU&quot;]/div[@class=&quot;ShellWrapper-module__root___V9OHs ShellWrapper-module__rootfocus___GLlI1 ShellWrapper-module__rootBorder___dKyVa&quot;]/div[1]/div[@class=&quot;ShellWrapper-module__wrapper___-Ugyc&quot;]/div[@class=&quot;ShellWrapper-module__content___UXPsu&quot;]/div[@class=&quot;AutoComplete-module__inputInner___4gegD&quot;]/input[@class=&quot;AutoComplete-module__textInput___Qh3I-&quot;]</value>
      <webElementGuid>3d3189a0-9373-4386-9b0f-cbb1e2b78e83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Rio De j']</value>
      <webElementGuid>ce47de80-5926-4bbb-b781-0b2262d7b27d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':R16dl1995:']/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>d26ceece-665c-422a-98a2-c48f23bb974e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>da101717-d5c0-437c-b8f6-6a2ead97ffd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Airport or city' and @type = 'text']</value>
      <webElementGuid>ac3b5f87-5e12-4311-9e0f-b8091a23ecd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
