<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Accept_AutoComplete-module__textInput_abe6fe_1_2</name>
   <tag></tag>
   <elementGuidId>ecffd748-80ea-4e20-a98c-343adf8a4a4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.AutoComplete-module__textInput___Qh3I-</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Rio']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Airport or city&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec979be3-5103-482e-b433-7c73c429800a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AutoComplete-module__textInput___Qh3I- </value>
      <webElementGuid>7c660203-d2e1-40fe-90c9-616506abe71d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Airport or city</value>
      <webElementGuid>5f42cebd-cc4c-4a16-af90-b390f036c41c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6ff10ecc-b49b-45d4-8613-1ab6796a9a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui-name</name>
      <type>Main</type>
      <value>input_text_autocomplete</value>
      <webElementGuid>bbd1bd70-0134-4956-bc09-fe46165cda3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>f3057915-5fe2-4167-bae4-85329de2ea2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>flights-searchbox_suggestions</value>
      <webElementGuid>e4ddce8d-b6be-4166-a3b8-d21b0eefa22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c6c7a1ce-21c4-4e09-89a6-dbca89bd0c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Rio</value>
      <webElementGuid>a3d0181f-3320-4403-9fa7-6081f2ecbdc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:R16dl1995:&quot;)/div[@class=&quot;Flyout-module__inner___yOVSv Popover-module__root___Hbald&quot;]/div[@class=&quot;LocationsDropDown-module__container___BjM+P&quot;]/div[@class=&quot;AutoComplete-module__wrapper___d3PlU&quot;]/div[@class=&quot;ShellWrapper-module__root___V9OHs ShellWrapper-module__rootfocus___GLlI1 ShellWrapper-module__rootBorder___dKyVa&quot;]/div[1]/div[@class=&quot;ShellWrapper-module__wrapper___-Ugyc&quot;]/div[@class=&quot;ShellWrapper-module__content___UXPsu&quot;]/div[@class=&quot;AutoComplete-module__inputInner___4gegD&quot;]/input[@class=&quot;AutoComplete-module__textInput___Qh3I-&quot;]</value>
      <webElementGuid>2c13a6c1-5af1-4123-a0a2-fe3db88145b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Rio']</value>
      <webElementGuid>6a9bf681-920a-493b-8284-650ed9427e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':R16dl1995:']/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>66a2e1d8-9897-48a2-ab31-dcde7cc64495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>bab0d3ff-36ff-4e9e-b28c-a56487d2c300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Airport or city' and @type = 'text']</value>
      <webElementGuid>f4f56eba-289e-4abd-8b18-aaaef0e68066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>c7804c8e-bbf0-4516-a236-0c7719d676ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
