<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Accept_AutoComplete-module__textInput_abe6fe_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16</name>
   <tag></tag>
   <elementGuidId>fcb19598-4608-4049-92c8-39d63734d2b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.AutoComplete-module__textInput___Qh3I-</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Rio De jabneir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Airport or city&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>346c0307-4078-4275-9cc8-69f9b9ce0d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AutoComplete-module__textInput___Qh3I- </value>
      <webElementGuid>a6fb4258-b4ac-4152-998c-1cb95693e53e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Airport or city</value>
      <webElementGuid>da4c3d1c-4c96-4dae-980c-ad17eaff2662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>672c8dc4-0351-4dfb-84f7-d16b2fb5bd92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui-name</name>
      <type>Main</type>
      <value>input_text_autocomplete</value>
      <webElementGuid>9008849c-cc1a-4cea-a035-10456a9e8d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>05a48f0d-d6c3-403d-9b11-03feec53e186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>flights-searchbox_suggestions</value>
      <webElementGuid>3d124bdf-85bf-4c52-b820-3391d5249a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3ff14a40-c493-4832-8ac2-eea41e1a1b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Rio De jabneir</value>
      <webElementGuid>02cec96e-7a54-4200-a536-82a880c253d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:R16dl1995:&quot;)/div[@class=&quot;Flyout-module__inner___yOVSv Popover-module__root___Hbald&quot;]/div[@class=&quot;LocationsDropDown-module__container___BjM+P&quot;]/div[@class=&quot;AutoComplete-module__wrapper___d3PlU&quot;]/div[@class=&quot;ShellWrapper-module__root___V9OHs ShellWrapper-module__rootfocus___GLlI1 ShellWrapper-module__rootBorder___dKyVa&quot;]/div[1]/div[@class=&quot;ShellWrapper-module__wrapper___-Ugyc&quot;]/div[@class=&quot;ShellWrapper-module__content___UXPsu&quot;]/div[@class=&quot;AutoComplete-module__inputInner___4gegD&quot;]/input[@class=&quot;AutoComplete-module__textInput___Qh3I-&quot;]</value>
      <webElementGuid>8c8fde96-99dc-49f9-ac32-2c09a0b78e4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Rio De jabneir']</value>
      <webElementGuid>18952359-d3ee-4a9d-aa77-244a65385cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':R16dl1995:']/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>6c849a3e-0b5c-463c-9259-ff0d85cc34d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>44e5543e-1d0a-496c-9f5e-296f0ca0a3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Airport or city' and @type = 'text']</value>
      <webElementGuid>41b22205-507e-4464-8168-f927875c4c3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
