<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Accept_AutoComplete-module__textInput_abe6fe_1_2_3_4_5_6_7_8</name>
   <tag></tag>
   <elementGuidId>c6cf83fe-d8df-441f-910d-62850445110e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.AutoComplete-module__textInput___Qh3I-</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Rio De ja']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Airport or city&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0c239fb-90ee-484a-846f-8df48b8a79ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AutoComplete-module__textInput___Qh3I- </value>
      <webElementGuid>52756033-da86-4d33-bf3e-43244652391c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Airport or city</value>
      <webElementGuid>908da847-5d3b-4547-bae4-11f4ce9b3203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>88556d81-15e1-459b-b896-09d376636a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui-name</name>
      <type>Main</type>
      <value>input_text_autocomplete</value>
      <webElementGuid>2e69445b-440b-48de-8b55-096a13eeb368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>3affcb42-c5d1-4e69-8ad5-74cb12b267ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>flights-searchbox_suggestions</value>
      <webElementGuid>d4e82e87-fc20-43f1-b395-afca03194054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7456b224-b974-4954-b337-244b55d1db22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Rio De ja</value>
      <webElementGuid>6160f587-abeb-42a6-ab18-60c9bd63b798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:R16dl1995:&quot;)/div[@class=&quot;Flyout-module__inner___yOVSv Popover-module__root___Hbald&quot;]/div[@class=&quot;LocationsDropDown-module__container___BjM+P&quot;]/div[@class=&quot;AutoComplete-module__wrapper___d3PlU&quot;]/div[@class=&quot;ShellWrapper-module__root___V9OHs ShellWrapper-module__rootfocus___GLlI1 ShellWrapper-module__rootBorder___dKyVa&quot;]/div[1]/div[@class=&quot;ShellWrapper-module__wrapper___-Ugyc&quot;]/div[@class=&quot;ShellWrapper-module__content___UXPsu&quot;]/div[@class=&quot;AutoComplete-module__inputInner___4gegD&quot;]/input[@class=&quot;AutoComplete-module__textInput___Qh3I-&quot;]</value>
      <webElementGuid>d0ca2578-4650-4472-ad1b-61561e82a622</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Rio De ja']</value>
      <webElementGuid>2fe5a2df-c817-452e-94fc-ec19a541a634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':R16dl1995:']/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>249087de-9723-4f4e-a0b3-6754f96086e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>4c7a38bc-12d3-4b33-90a3-a6adc51ed6ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Airport or city' and @type = 'text']</value>
      <webElementGuid>ab3bc3e5-bdfa-442c-94fe-012722282736</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
