<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Accept_AutoComplete-module__textInput_abe6fe_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18</name>
   <tag></tag>
   <elementGuidId>e7eb311d-a21e-4296-a885-aae65a3124cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.AutoComplete-module__textInput___Qh3I-</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Rio De jabneiro ']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Airport or city&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6093c3ad-4870-4931-97ee-a77d4613b6b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AutoComplete-module__textInput___Qh3I- </value>
      <webElementGuid>33e09065-ec72-4574-9e05-00d01d9f0a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Airport or city</value>
      <webElementGuid>3e6f09ce-d656-4a9f-8e5d-2eb536db5280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>62591163-a591-4b31-a4d3-bfd6f4dbc0f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui-name</name>
      <type>Main</type>
      <value>input_text_autocomplete</value>
      <webElementGuid>8f2eb1cc-b962-47f0-89c8-a42c4b335e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>74b02af0-7040-47cf-8cb6-050f40050cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>flights-searchbox_suggestions</value>
      <webElementGuid>2c14d8dc-0d4b-40ac-8f9e-e42f199dff19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9da8fc76-8f7f-4c49-aa4d-397056b669f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Rio De jabneiro </value>
      <webElementGuid>a6db4674-b225-40bc-acee-bae2c38209ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:R16dl1995:&quot;)/div[@class=&quot;Flyout-module__inner___yOVSv Popover-module__root___Hbald&quot;]/div[@class=&quot;LocationsDropDown-module__container___BjM+P&quot;]/div[@class=&quot;AutoComplete-module__wrapper___d3PlU&quot;]/div[@class=&quot;ShellWrapper-module__root___V9OHs ShellWrapper-module__rootfocus___GLlI1 ShellWrapper-module__rootBorder___dKyVa&quot;]/div[1]/div[@class=&quot;ShellWrapper-module__wrapper___-Ugyc&quot;]/div[@class=&quot;ShellWrapper-module__content___UXPsu&quot;]/div[@class=&quot;AutoComplete-module__inputInner___4gegD&quot;]/input[@class=&quot;AutoComplete-module__textInput___Qh3I-&quot;]</value>
      <webElementGuid>9a2ea2fe-1ef0-43fe-89e4-506ae9c211ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Rio De jabneiro ']</value>
      <webElementGuid>1e7a0445-a249-42f2-a9df-e82a5fad569c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':R16dl1995:']/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>82855665-0747-4aa1-92f6-e5823753e5ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>ae91b9be-966c-4cbf-9f3f-d6687635eeb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Airport or city' and @type = 'text']</value>
      <webElementGuid>418e44dc-a530-43ee-b08e-cb356a3783b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
