<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select age at time of flying01234567_433fd8</name>
   <tag></tag>
   <elementGuidId>f1b90c4a-4be6-4497-ac75-4cae8847d647</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id=':rt:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;1st child's age&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d6c46077-8dce-4a86-b14d-ea9edbc29a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>InputSelect-module__field___tLmBd</value>
      <webElementGuid>7328d3b1-d3aa-4718-b9d5-030aeb208f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sr_occupancy_children_age_0</value>
      <webElementGuid>f0dea7bf-6989-4150-99b2-83da42e2e9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui-name</name>
      <type>Main</type>
      <value>select_occupancy_children_age_0</value>
      <webElementGuid>bf54cee1-7978-4f60-80b1-41a5676a3065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:rt:</value>
      <webElementGuid>582e56e6-dec8-47c3-bb59-074613cf2de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:rt:-note</value>
      <webElementGuid>34f1e5be-bee9-469d-b2a8-01076c2955c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select age at time of flying01234567891011121314151617</value>
      <webElementGuid>ec1db099-ae3b-4513-ab19-8f9b73989781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rt:&quot;)</value>
      <webElementGuid>715b4af1-01c7-415d-ab2c-de1b5b6918c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id=':rt:']</value>
      <webElementGuid>4079d3df-0e4f-497d-8bd8-75b182f5cb9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':R4tl1995:']/div/div/div/div/div[3]/div/div/select</value>
      <webElementGuid>c6e11b8f-4d33-4f8a-9951-3a4f0b02b990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age 0 - 17'])[1]/following::select[1]</value>
      <webElementGuid>601acd6e-8409-42af-9c5f-5b26c4e75745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the age this child will be on the date of your final flight'])[1]/preceding::select[1]</value>
      <webElementGuid>75c5d3e0-f790-43bc-8846-bede897abf6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/select</value>
      <webElementGuid>20ff74a6-d4b6-4810-a7ea-23694d0983ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'sr_occupancy_children_age_0' and @id = ':rt:' and (text() = 'Select age at time of flying01234567891011121314151617' or . = 'Select age at time of flying01234567891011121314151617')]</value>
      <webElementGuid>1d739b1f-043d-40ff-beab-af11a73e4192</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
