<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select age at time of flying01234567_433fd8_1</name>
   <tag></tag>
   <elementGuidId>34f7244b-56f1-49fb-90f8-d847be0e7a91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id=':ru:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;2nd child's age&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e827a452-897c-4e18-bc4c-2e81cd1cd94f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>InputSelect-module__field___tLmBd</value>
      <webElementGuid>c018efff-08a7-4450-a002-c04f14f9fd99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sr_occupancy_children_age_1</value>
      <webElementGuid>b0f82463-39f8-4462-8545-f19fc9bd563b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui-name</name>
      <type>Main</type>
      <value>select_occupancy_children_age_1</value>
      <webElementGuid>b6f8f6eb-dc71-4f20-8c4e-6e0fd7e18749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:ru:</value>
      <webElementGuid>6d826bae-065c-4726-9577-19da6ce3d1a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:ru:-note</value>
      <webElementGuid>88f31581-ef2f-42f4-af63-aa3902ef3206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select age at time of flying01234567891011121314151617</value>
      <webElementGuid>66993b28-7e9f-4c96-9d42-89211359ea42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:ru:&quot;)</value>
      <webElementGuid>22f16cbe-fef8-462e-b87b-c22a389de465</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id=':ru:']</value>
      <webElementGuid>36a7258a-3961-497d-b8b2-bac50b582298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':R4tl1995:']/div/div/div/div/div[3]/div[2]/div/select</value>
      <webElementGuid>a44fdb8b-da25-4aa9-89e3-463fb993b58e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the age this child will be on the date of your final flight'])[1]/following::select[1]</value>
      <webElementGuid>7ffecd41-6fd9-4bbc-9227-6001e0f74074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the age this child will be on the date of your final flight'])[2]/preceding::select[1]</value>
      <webElementGuid>8b81e8d5-676a-4602-a21f-20de05c4f1e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[1]/preceding::select[1]</value>
      <webElementGuid>905fa833-debd-4783-99b6-671ae4d26ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>0af17f09-5756-40fb-a068-7fd4a7af4a7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'sr_occupancy_children_age_1' and @id = ':ru:' and (text() = 'Select age at time of flying01234567891011121314151617' or . = 'Select age at time of flying01234567891011121314151617')]</value>
      <webElementGuid>ed12a463-1879-4377-976c-9eeb192395e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
