<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_25</name>
   <tag></tag>
   <elementGuidId>f4b74679-dffc-43c9-bd83-0f08eb88bc41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':R4ll1995:']/div/div/div/div/div/div/table/tbody/tr[4]/td[6]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;25 January 2025&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>16fa5a99-9275-4460-a6c6-231c01f832a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>48fa048f-5aaf-456b-8097-940194dbcd4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Calendar-module__date___BoBZ+ Calendar-module__date--hoverable___jwePs Calendar-module__date--selected___0Lmxz Calendar-module__date--selected-end___VtFgq</value>
      <webElementGuid>2a8d8b47-0e17-48c5-b016-6ed7ab53235e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>2025-01-25</value>
      <webElementGuid>a54d294c-b9b8-4484-8fa4-2d3d1dfe188d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ed1329d5-8e04-445c-99d7-40f4ea827cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6a32e142-deb5-42ed-affe-171930be24ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>25 January 2025</value>
      <webElementGuid>9de1b96e-f3ce-45ec-b461-b5f1a80b607c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>e9ed36d6-b3a7-45eb-a7a7-5083dddbba21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:R4ll1995:&quot;)/div[@class=&quot;Flyout-module__inner___yOVSv Popover-module__root___Hbald Popover-module__root--fill___GfL+b&quot;]/div[@class=&quot;DateDropDown-module__popovercontainer___ZHcTt&quot;]/div[@class=&quot;DateDropDown-module__calendarWrapperInner___qvRnO&quot;]/div[@class=&quot;Calendar-module__root___CUKVx Calendar-module__root--full-height___XpvSS&quot;]/div[@class=&quot;Calendar-module__content___UHIgA&quot;]/div[@class=&quot;Calendar-module__monthWrapper___T0gG4&quot;]/table[@class=&quot;Calendar-module__dates___RSax3&quot;]/tbody[1]/tr[4]/td[@class=&quot;Calendar-module__cell___7S9c-&quot;]/span[@class=&quot;Calendar-module__date___BoBZ+ Calendar-module__date--hoverable___jwePs Calendar-module__date--selected___0Lmxz Calendar-module__date--selected-end___VtFgq&quot;]</value>
      <webElementGuid>8f4f2ece-cc9b-40b2-8544-8dd2f71eabb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':R4ll1995:']/div/div/div/div/div/div/table/tbody/tr[4]/td[6]/span</value>
      <webElementGuid>c57cd515-b3ed-48ce-82d4-5d7f2482bb74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[1]/following::span[73]</value>
      <webElementGuid>e217eaa4-8cd1-4d77-ab67-4c83504fa680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[73]</value>
      <webElementGuid>e53f8cc2-d557-4457-9767-006b6221f760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='February 2025'])[1]/preceding::span[21]</value>
      <webElementGuid>4da438b0-2bc8-4432-b520-06cc99da8e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mo'])[2]/preceding::span[21]</value>
      <webElementGuid>d877c534-a4c9-464e-83d6-32ebae502151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[6]/span</value>
      <webElementGuid>44e2454d-1cd9-48a6-b6bd-9a6e65f3feb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '25' or . = '25')]</value>
      <webElementGuid>4e2f586f-3def-448e-9c4a-621f2f9bb4c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
