<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_22</name>
   <tag></tag>
   <elementGuidId>5842bd08-6b5a-4406-82a5-dd2da9435f70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':R4ll1995:']/div/div/div/div/div/div[2]/table/tbody/tr[4]/td[6]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;22 February 2025&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c752bd24-b196-4a42-b68e-95da94e83c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>54e07fcf-73d3-4478-8985-990c333d0bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Calendar-module__date___BoBZ+ Calendar-module__date--hoverable___jwePs Calendar-module__date--in-range___SA6D0</value>
      <webElementGuid>0471fc5b-5740-4444-8531-050b0bde698e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>2025-02-22</value>
      <webElementGuid>a0d708ba-66c9-412f-9aaf-ccdcbf5d654a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a5b98c8a-2db6-4c8d-86c8-8d4b798998a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6416e4e0-4feb-4303-9c3a-6a387ee23b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>22 February 2025</value>
      <webElementGuid>f34f0cbf-d030-4ed7-90e0-2b72480780a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>bc84ec3a-5044-44f5-bd5d-29b5e20d05e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:R4ll1995:&quot;)/div[@class=&quot;Flyout-module__inner___yOVSv Popover-module__root___Hbald Popover-module__root--fill___GfL+b&quot;]/div[@class=&quot;DateDropDown-module__popovercontainer___ZHcTt&quot;]/div[@class=&quot;DateDropDown-module__calendarWrapperInner___qvRnO&quot;]/div[@class=&quot;Calendar-module__root___CUKVx Calendar-module__root--full-height___XpvSS&quot;]/div[@class=&quot;Calendar-module__content___UHIgA&quot;]/div[@class=&quot;Calendar-module__monthWrapper___T0gG4&quot;]/table[@class=&quot;Calendar-module__dates___RSax3&quot;]/tbody[1]/tr[4]/td[@class=&quot;Calendar-module__cell___7S9c-&quot;]/span[@class=&quot;Calendar-module__date___BoBZ+ Calendar-module__date--hoverable___jwePs Calendar-module__date--in-range___SA6D0&quot;]</value>
      <webElementGuid>ddd6bcbc-d166-4ea2-ba6f-7de8e6ffdeeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':R4ll1995:']/div/div/div/div/div/div[2]/table/tbody/tr[4]/td[6]/span</value>
      <webElementGuid>544a70ef-ceec-4d50-a09f-dd108fac7a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[2]/following::span[64]</value>
      <webElementGuid>6e36a431-edc3-4a7b-b564-a6525d6df358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[2]/following::span[64]</value>
      <webElementGuid>a25d329a-ed00-4c5a-9595-d1caccb1bd24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[4]/td[6]/span</value>
      <webElementGuid>bbf4eef2-ca83-44c3-9885-23114741bdb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '22' or . = '22')]</value>
      <webElementGuid>8c1a0a14-8744-4132-b431-98b9b566100b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
