<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Done</name>
   <tag></tag>
   <elementGuidId>648dbc69-a0d1-4cb4-a195-6660fad104ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':R4tl1995:']/div/div/div[2]/div/div/div/div[2]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Done&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4aac804b-8f6d-4440-bf46-918c8cf3008c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button-module__text___sRRzg</value>
      <webElementGuid>869d4a1f-e82c-4fe5-9084-d4f83366c155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done</value>
      <webElementGuid>37e3e1e6-422e-4cfa-89c3-d7ceff843865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:R4tl1995:&quot;)/div[@class=&quot;Flyout-module__inner___yOVSv Popover-module__root___Hbald Popover-module__root--fill___GfL+b&quot;]/div[@class=&quot;OccupancyDropDown-module__content___ve5Q2&quot;]/div[@class=&quot;OccupancyDropDown-module__contentFooter___4boFb&quot;]/div[@class=&quot;ActionBar-module__root___Z6YQB&quot;]/div[@class=&quot;Stack-module__root___ohshd Stack-module__root--direction-column___xJDCe Stack-module__root--grow-false___eaLO- ActionBar-module__container___eh4Sp ActionBar-module__container--size-medium___vzJrw ActionBar-module__container--elevated-false___qaePz&quot;]/div[@class=&quot;Stack-module__root___ohshd Stack-module__root--direction-row___3r3Pe Stack-module__root--align-items-center___EpLLc Stack-module__root--nowrap___YFYa0 Stack-module__root--grow-false___eaLO- ActionBar-module__content___vP+uR&quot;]/div[2]/button[@class=&quot;Actionable-module__root___ph-jy Button-module__root___RNgyk Button-module__root--variant-primary___3zF7+ Button-module__root--size-medium___fCFP3 Button-module__root--wide___vGG-n Button-module__root--variant-primary-action___CWu4O Actionable-module__root--wide-true___V0+an&quot;]/span[@class=&quot;Button-module__text___sRRzg&quot;]</value>
      <webElementGuid>bf3ac9af-89c1-4320-b0a2-2d4769d60485</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':R4tl1995:']/div/div/div[2]/div/div/div/div[2]/button/span</value>
      <webElementGuid>fb6deeec-bd2a-4a56-a8da-175d67a53e0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the age this child will be on the date of your final flight'])[2]/following::span[1]</value>
      <webElementGuid>fa5df2d9-683f-4e7d-ba06-02f1c673434a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Done']/parent::*</value>
      <webElementGuid>10138a65-a869-4536-9e81-85b018556bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/button/span</value>
      <webElementGuid>d405d5f5-d554-4f1f-9e39-0825b29bc2cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Done' or . = 'Done')]</value>
      <webElementGuid>8e0425e5-77dd-4c84-9a3a-650b3991d7ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
