<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_25</name>
   <tag></tag>
   <elementGuidId>f4b74679-dffc-43c9-bd83-0f08eb88bc41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':R4ll1995:']/div/div/div/div/div/div/table/tbody/tr[4]/td[6]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;25 January 2025&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fae2e4fa-693d-47cd-a880-ea729133701e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>990131fe-0ad1-4925-a74b-db9459c8a89a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Calendar-module__date___BoBZ+ Calendar-module__date--hoverable___jwePs Calendar-module__date--selected___0Lmxz Calendar-module__date--selected-end___VtFgq</value>
      <webElementGuid>d0d26aa3-5b2f-4269-8019-ee8b0b91bd0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>2025-01-25</value>
      <webElementGuid>45d327ae-dc73-4cac-aab9-85f93482fb66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b727ade6-4496-4822-a326-9f5a0cd798be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3816416c-4080-46c0-94e9-50e610e57ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>25 January 2025</value>
      <webElementGuid>40f9e626-c793-45f3-9e3c-a8cb8e0f67e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>802ef433-2284-44b4-85c4-53e561d0c861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:R4ll1995:&quot;)/div[@class=&quot;Flyout-module__inner___yOVSv Popover-module__root___Hbald Popover-module__root--fill___GfL+b&quot;]/div[@class=&quot;DateDropDown-module__popovercontainer___ZHcTt&quot;]/div[@class=&quot;DateDropDown-module__calendarWrapperInner___qvRnO&quot;]/div[@class=&quot;Calendar-module__root___CUKVx Calendar-module__root--full-height___XpvSS&quot;]/div[@class=&quot;Calendar-module__content___UHIgA&quot;]/div[@class=&quot;Calendar-module__monthWrapper___T0gG4&quot;]/table[@class=&quot;Calendar-module__dates___RSax3&quot;]/tbody[1]/tr[4]/td[@class=&quot;Calendar-module__cell___7S9c-&quot;]/span[@class=&quot;Calendar-module__date___BoBZ+ Calendar-module__date--hoverable___jwePs Calendar-module__date--selected___0Lmxz Calendar-module__date--selected-end___VtFgq&quot;]</value>
      <webElementGuid>8519e7ec-873b-4d1d-bc53-9d4ee8ed545a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':R4ll1995:']/div/div/div/div/div/div/table/tbody/tr[4]/td[6]/span</value>
      <webElementGuid>d5abe6c2-d6ff-4a91-95bf-3406bed7b4f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[1]/following::span[73]</value>
      <webElementGuid>27f8dbf1-d56e-4a14-8ca0-6a8660ccc4eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[73]</value>
      <webElementGuid>59ff9c1f-e4d7-4dc1-863a-2b9c1288df93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='February 2025'])[1]/preceding::span[21]</value>
      <webElementGuid>bad7efe7-a59f-4350-891a-eff64d21cbd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mo'])[2]/preceding::span[21]</value>
      <webElementGuid>9909d899-8327-4f08-bcdf-65ce40942fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[6]/span</value>
      <webElementGuid>8f3cbb25-67ac-48d6-b77e-2c1c5afe2e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '25' or . = '25')]</value>
      <webElementGuid>cc5c9301-66aa-45df-bbf8-bfe007856a90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
