<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_23</name>
   <tag></tag>
   <elementGuidId>c87649d2-9c83-4576-ac6f-6630a3676720</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':R4ll1995:']/div/div/div/div/div/div[2]/table/tbody/tr[4]/td[7]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;23 February 2025&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2027b4fc-6b13-4c6b-9f59-2806e9ac9818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>98417d9f-043b-464c-b152-adc176565bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Calendar-module__date___BoBZ+ Calendar-module__date--hoverable___jwePs Calendar-module__date--in-range___SA6D0</value>
      <webElementGuid>4dfeb834-527e-4f55-82a7-d1157875d2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>2025-02-23</value>
      <webElementGuid>c240392d-1716-4e5b-9aea-6b672bc043d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d39f27f3-9d06-49a9-a145-0278dc6950f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2b4c2163-5c04-4250-b369-24f1f1b64613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>23 February 2025</value>
      <webElementGuid>c843ffcf-1774-4c2c-8b2f-0f33aa695331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>4f2aa82d-95c5-4860-a22a-a670975e873b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:R4ll1995:&quot;)/div[@class=&quot;Flyout-module__inner___yOVSv Popover-module__root___Hbald Popover-module__root--fill___GfL+b&quot;]/div[@class=&quot;DateDropDown-module__popovercontainer___ZHcTt&quot;]/div[@class=&quot;DateDropDown-module__calendarWrapperInner___qvRnO&quot;]/div[@class=&quot;Calendar-module__root___CUKVx Calendar-module__root--full-height___XpvSS&quot;]/div[@class=&quot;Calendar-module__content___UHIgA&quot;]/div[@class=&quot;Calendar-module__monthWrapper___T0gG4&quot;]/table[@class=&quot;Calendar-module__dates___RSax3&quot;]/tbody[1]/tr[4]/td[@class=&quot;Calendar-module__cell___7S9c-&quot;]/span[@class=&quot;Calendar-module__date___BoBZ+ Calendar-module__date--hoverable___jwePs Calendar-module__date--in-range___SA6D0&quot;]</value>
      <webElementGuid>28c1eee7-e5e5-49c9-8143-c0d080183cc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':R4ll1995:']/div/div/div/div/div/div[2]/table/tbody/tr[4]/td[7]/span</value>
      <webElementGuid>f98fd4cd-56bc-45c0-b487-2d0685d17a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[2]/following::span[67]</value>
      <webElementGuid>f022b658-d7a7-4438-8a34-0914278f73d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[2]/following::span[67]</value>
      <webElementGuid>8599d590-a60b-453c-9c01-9ff0d563fece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[4]/td[7]/span</value>
      <webElementGuid>bb5507f7-bda9-46e3-adb1-ae713fe6b8b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '23' or . = '23')]</value>
      <webElementGuid>d5d2f976-6f09-4572-9f20-57c95da31634</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
