<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Register</name>
   <tag></tag>
   <elementGuidId>4fe46321-b59a-4248-a829-43ab7a992aab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/header/div/nav/div[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.a83ed08757.c21c56c305.bf0537ecb5.ab98298258.af7297d90d.js-header-login-link > span.e4adce92df</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;header-sign-up-button&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>862f757b-1e13-4d4a-bc46-b525d8769130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e4adce92df</value>
      <webElementGuid>0ffb83de-af78-4464-8687-063baac7bdc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>3160c7b7-5a91-400b-857d-a04ca500634c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[1]/div[1]/div[@class=&quot;web-shell-header-mfe ab4f62cc7e a1902a1d4e&quot;]/header[@class=&quot;Header_root&quot;]/div[@class=&quot;ffb9c3d6a3&quot;]/nav[@class=&quot;Header_bar&quot;]/div[@class=&quot;c624d7469d f034cf5568 dab7c5c6fa c62ffa0b45 a3214e5942&quot;]/a[@class=&quot;a83ed08757 c21c56c305 bf0537ecb5 ab98298258 af7297d90d js-header-login-link&quot;]/span[@class=&quot;e4adce92df&quot;]</value>
      <webElementGuid>491abadf-f496-4aec-8a3a-76482f6055a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/header/div/nav/div[2]/a/span</value>
      <webElementGuid>9390d0a4-3999-494a-b817-65ec2b636b85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to main content'])[1]/following::span[7]</value>
      <webElementGuid>6ec036df-ede9-4fc8-a7d4-61e379a71e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/preceding::span[1]</value>
      <webElementGuid>be17a72d-4e12-4ae7-9686-3c2449f350b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stays'])[1]/preceding::span[3]</value>
      <webElementGuid>cf723971-2d50-427c-a98c-4d848dd10039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Register']/parent::*</value>
      <webElementGuid>7a7c4168-fb02-45ff-aaef-542655a654ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/span</value>
      <webElementGuid>1d55ad23-9d61-4f4f-80e8-0be7c8cf4994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Register' or . = 'Register')]</value>
      <webElementGuid>a5933bef-450e-40c9-94f4-4a6707caa537</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
