<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Your Message_a-xyj3lj2wicu6</name>
   <tag></tag>
   <elementGuidId>180518a1-58f8-43dc-bd95-584cca7a04bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-xyj3lj2wicu6&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-xyj3lj2wicu6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;a-xyj3lj2wicu6&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>212b5ef8-acea-4639-9051-83b971c5fff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>345436e1-af1e-4fba-8541-d52beb8242b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>5777d553-2df1-4d6a-8460-433fb53ef4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>49fd6496-387b-4a44-af57-7239057c604b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>7fc1d82a-6d23-4f0b-915f-a16de4395c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-xyj3lj2wicu6</value>
      <webElementGuid>cebfedb8-8443-476d-8a56-a789ec5c5653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>273156b9-e5b1-4db4-a8cf-c7fe56c7950a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>2bc1c93f-c150-44cc-a90b-c816207c9014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>986bf166-d16a-46ec-b9fa-330fef761ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcRmG4hAAAAAFu7zOI-lpnsPm_-4nqSvKz8Am23&amp;co=aHR0cHM6Ly93d3cub3JhbmdlaHJtLmNvbTo0NDM.&amp;hl=en&amp;type=image&amp;v=pPK749sccDmVW_9DSeTMVvh2&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=mbqiwmrk3zam</value>
      <webElementGuid>2a3e6608-364f-4fda-9980-8d7f68f82f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lf-yt-playback-inspected-xbp1oaewrnz7edvj</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ea7febfc-f304-4e0f-951c-855589f83b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lf-vimeo-playback-inspected-xbp1oaewrnz7edvj</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9b701ece-7b42-4c33-8f0f-9d87a25240b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Nocaptcha-Form_getForm_Captcha&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>89e250cc-20e9-47f1-8560-060957d6a450</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-xyj3lj2wicu6']</value>
      <webElementGuid>662b10a7-0e52-4f49-9013-376b8498891a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Nocaptcha-Form_getForm_Captcha']/div/div/iframe</value>
      <webElementGuid>ff09a557-cbdc-4156-aff1-f08a5b4b5fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/iframe</value>
      <webElementGuid>a1e8b91b-64bb-4ba9-8828-60492608eaef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-xyj3lj2wicu6' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcRmG4hAAAAAFu7zOI-lpnsPm_-4nqSvKz8Am23&amp;co=aHR0cHM6Ly93d3cub3JhbmdlaHJtLmNvbTo0NDM.&amp;hl=en&amp;type=image&amp;v=pPK749sccDmVW_9DSeTMVvh2&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=mbqiwmrk3zam']</value>
      <webElementGuid>a4f55af3-62f9-423e-a6d3-c0da82f6339a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
