<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>awswaf-captcha-ing.com-2b4</name>
   <tag></tag>
   <elementGuidId>4e5a6a58-6ed3-4472-b24d-6a2ff0548a3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div/div/div/div/div[2]/div/div/awswaf-captcha</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>awswaf-captcha</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>awswaf-captcha</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>awswaf-captcha</value>
      <webElementGuid>c5858238-9cb5-4445-9680-dec088bb3f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>23178229-af70-4c1a-9a62-07bb1ea9c2a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;app&quot;]/div[@class=&quot;access-container bui_font_body&quot;]/div[@class=&quot;access-panel-container&quot;]/div[@class=&quot;access-panel nw-access-panel&quot;]/div[@class=&quot;transition-container&quot;]/div[@class=&quot;animate-height&quot;]/div[@class=&quot;sliding-panel&quot;]/div[@class=&quot;transition bui-panel-body&quot;]/div[@class=&quot;v3PQKnrwstNw3Fp4rB_v ZDzkc5HybZJchOZiExiQ lbkyKXfdfIDAMGb_xv0E&quot;]/div[@class=&quot;nw-signin&quot;]/div[@class=&quot;v3PQKnrwstNw3Fp4rB_v ZDzkc5HybZJchOZiExiQ lbkyKXfdfIDAMGb_xv0E&quot;]/div[1]/awswaf-captcha[1]</value>
      <webElementGuid>1017eb2c-d504-4531-90ca-98362d0bb0bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div/div/div/div/div[2]/div/div/awswaf-captcha</value>
      <webElementGuid>0193a4d2-8295-496e-aa07-2a49f9f66a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//awswaf-captcha</value>
      <webElementGuid>396b0edf-eed8-42dd-8ae9-2160eb318b9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
